<template>
    <el-container>
        <el-header>Header</el-header>
        <el-container>
            <el-aside>Aside</el-aside>
            <el-main>Main</el-main>
            <el-aside>Aside</el-aside>
        </el-container>
        <el-footer>Footer</el-footer>
    </el-container>
</template>
